### ISSUE TITLE
Support für 1.6.0p2 CEE

### ISSUE THREAD

**Issue by robertoschwald** [HenriWahl/checkmk-agent-plugin-yum#19]
Derzeit läuft die Extension nicht in der 1.6.0p2 EE appliance.

Error in bakery plugin "yum": 'module' object has no attribute 'paths'

```
Traceback (most recent call last):
  File "/omd/sites/xxx/lib/python/cmk_base/cee/agent_bakery.py", line 364, in execute_bakery_plugin
    bake_func(*func_args)
  File "/omd/sites/xxx/local/share/check_mk/agents/bakery/yum", line 13, in bake_yum
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/yum", target_dir + "/yum")
AttributeError: 'module' object has no attribute 'paths'
```

**Comment by robertoschwald** [comment]
Hab gesehen das dies schon gefixt ist in 3914f16d7617f8008fc1a1b74143e1cc00012f7d

**Comment by robertoschwald** [comment]
Habe die Änderungen aus 3914f16 lokal übernommen. Läuft. Hoffe es gibt bald eine neue Version..
