### ISSUE TITLE
mkp install issues 

### ISSUE THREAD

**Issue by 47k** [HenriWahl/checkmk-agent-plugin-yum#38]
Traceback (most recent call last):
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1674, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1651, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1104, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/omd/sites/Test/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/Test/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/check_mk.py", line 654, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 89, in do_packaging
    f(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 288, in package_install
    packaging.install_by_path(path)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 350, in install_by_path
    return install(file_object=cast(BinaryIO, f))
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 354, in install
    package = _get_package_info_from_package(file_object)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 485, in _get_package_info_from_package
    tar = tarfile.open(fileobj=file_object, mode="r:gz")
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1678, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

**Comment by schoekek** [comment]
Pls wait until #37 merge....

**Comment by HenriWahl** [comment]
Merge is done now.

**Comment by 47k** [comment]
`wget https://github.com/HenriWahl/checkmk-agent-plugin-yum/blob/master/yum-2.2.1.mkp`

`OMD[Test]:~$ mkp install /home/overlord/yum-2.2.1.mkp
Traceback (most recent call last):
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1674, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1651, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1104, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/omd/sites/Test/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/Test/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/check_mk.py", line 654, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 89, in do_packaging
    f(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 288, in package_install
    packaging.install_by_path(path)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 352, in install_by_path
    return install(file_object=cast(BinaryIO, f))
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 356, in install
    package = _get_package_info_from_package(file_object)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 490, in _get_package_info_from_package
    tar = tarfile.open(fileobj=file_object, mode="r:gz")
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1678, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file`

Issue still persist

**Comment by gurubert** [comment]
You downloaded an HTML page. The correct URL for the binary MKP ist https://github.com/HenriWahl/checkmk-agent-plugin-yum/raw/master/yum-2.2.1.mkp

**Comment by HenriWahl** [comment]
Looks like being closeable.
