### ISSUE TITLE
Enterprise edition required?

### ISSUE THREAD

**Issue by dkastens** [HenriWahl/checkmk-agent-plugin-yum#55]
Hi, I installed the plugin on the CheckMK Raw Edition. It works, but I see the following messages in the web.log:

```
2022-12-07 16:25:05,929 [40] [cmk.web 1656] Failed to load plugin /omd/sites/rz/local/share/check_mk/web/plugins/wato/yum_cee.py: No module named 'cmk.gui.cee'
Traceback (most recent call last):
  File "/omd/sites/rz/lib/python3/cmk/gui/utils/__init__.py", line 186, in load_web_plugins
    exec(f.read(), globalvars)
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'cmk.gui.cee'
```
The module cmk.gui.cee doesn't exist in the Raw Edition. Is this correct?

Thanks,
Dirk

**Comment by HenriWahl** [comment]
Hi @dkastens,

Enterprice edition is required for GUI configuration which is not possible in community edition. So this error is harmless.
Maybe a good idea to put the imports into a try/except block to avoid cluttering the logs.

**Comment by dkastens** [comment]
Hi,
thanks for the reply. I'm new to check_mk, so I have to learn a lot. I will try to change the imports.
